GoogleProject/GoogleProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),  
]

GoogleProject/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.main_view, name="main_view"),
    path("google/", views.main_view, name="google"),
    path("terms and services/", views.term_view, name="term"),


]

GoogleProject/myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('base/', views.base_view, name='base'),
    path('terms_of_service/', views.terms_of_service_view, name='terms_of_service'),
]

GoogleProject/main/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse

# Create your views here.

def main_view(request:HttpRequest):

    return render(request, "main/google.html")



def term_view(request:HttpRequest):

    return render(request, "main/term.html")

GoogleProject/myapp/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'myapp/home.html')

def base_view(request):
    return render(request, 'myapp/base.html')

def terms_of_service_view(request):
    return render(request, 'myapp/terms_of_service.html')

GoogleProject/main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Google{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style2.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"/>

  </head>
  <body>
    <!-- Top Navigation Bar -->
     <div class="top-container">
    <div class="top-nav">
      <a href="#">Gmail</a>
      <a href="#">Images</a>
      <img class="grid-icon" src="{% static 'images/ix.png' %}" alt="Menu" />
      <button class="sign-in">Sign In</button>
    </div>
     </div>

    <!-- Main Content Block -->
    <div>{% block content %} {% endblock %}</div>

    <!-- Footer -->
    <section class="footer">
      <div class="footer-top">
        <div>Saudi Arabia</div>
      </div>
      <div class="footer-links">
        <div class="links">
          <a href="#">About</a>
          <a href="#">Advertising</a>
          <a href="#">Business</a>
          <a href="#">How Search works</a>
        </div>
        <div class="links">
          <a href="#">Privacy</a>
          <a href="{% url 'main:term'%}">Terms</a>
          <a href="#">Settings</a>
        </div>
      </div>
    </section>
  </body>
</html>

GoogleProject/main/templates/main/google.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Google{% endblock %}

{% block content %}
<div class="logo">
    <img src="{% static 'images/google-logo.png' %}" alt="Google Logo" />
</div>

<!-- Search Box -->
 <div class="search-container">
    <div class="search-box">
        <input type="text" class="search-input" placeholder="Search Google or type a URL">
        <button class="icon-button icon-search">
            <img src="{% static 'images/search.png' %}" alt="Search" />
        </button>
        <button class="icon-button icon-mic">
            <img src="{% static 'images/mircophone.png' %}" alt="Microphone" />
        </button>
        <button class="icon-button icon-camera">
            <img src="{% static 'images/camera.png' %}" alt="Camera" />
        </button>
    </div>
  </div>

<!-- Buttons -->
<div class="buttons">
    <button>Google Search</button>
    <button>I'm Feeling Lucky</button>
</div>

<!-- Language Offer -->
<div class="language">
    <p>Google offered in: <a href="#">العربية</a></p>
</div>

{% endblock %}

GoogleProject/main/templates/main/term.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Google Terms of Service{% endblock %}

{% block content %}
<div class="content">
    <!-- Header Image -->
    <div class="header-image">
        <img src="{% static 'images/term 2.png' %}" alt="Google Terms of Service Image"/>
    </div>

    <!-- Terms Text -->
    <div class="terms-text">
        <h1>Google Terms of Service</h1>
        <p> Effective 5 January 2022 | <a href="https://policies.google.com/terms/archive">Archived versions</a> | 
            <a href="chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.gstatic.com/policies/terms/pdf/20240522/ks8shls0/google_terms_of_service_en-GB.pdf">Download PDF</a>
        </p>
        <p><strong>Country version:</strong> Saudi Arabia</p>

        <h2>What’s covered in these terms</h2>
        <h3>
          We know it's tempting to skip these Terms of Service, but it's
          important to establish what you can expect from us as you use Google
          services, and what we expect from you.
        </h3>

        <p>These Terms of Service reflect <a href="https://about.google/intl/en-GB_SA/how-our-business-works/">the way that our business works</a>, the laws that apply to our company, and 
          <a href="https://about.google/philosophy/">certain things that we’ve always believed to be true</a>.
        </p>

        <div class="terms-details">
            <ul>
                <li><a href="#">What you can expect from us</a>, which describes how we provide and develop our services.</li>
                <li><a href="#">What we expect from you</a>, which establishes certain rules for using our services.</li>
                <li><a href="#">Content in Google services</a>, which describes the intellectual property rights to the content that you find in our services.</li>
                <li><a href="#">In case of problems or disagreements</a>, which describes other legal rights that you have, and what to expect if someone violates these terms.</li>
            </ul>
        
            <p>Understanding these terms is important because, by accessing or using our services, you're agreeing to these terms.</p>
        
            <p>Besides these terms, we also publish a <a href="https://policies.google.com/privacy">Privacy Policy</a>. Although it’s not part of these terms, we encourage you to read it to better understand how you can 
                <a href="#">update</a>, <a href="#">manage</a>, <a href="#">export</a>, and <a href="#">delete your information</a>.
            </p>
        </div>
    </div>
</div>
{% endblock %}

GoogleProject/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Google Search{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'myapp/styles/styles.css' %}">
    
</head>
<body>
    <div class="navbar">
        <div class="navbar-links">
            <a href="{% url 'myapp:home' %}">Google</a>
            <a href="">Images</a>
        </div>
        <div class="navbar-icons">
            <a href="{% url 'myapp:home' %}">
                <button type="submit" class="icon-button">
                    <img src="{% static 'myapp/images/image.png' %}" />
                </button>
            </a>
        </div>
        <div class="navbar-signin">
            <button class="signin-button">Sign In</button>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

GoogleProject/myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}

{% block title %}Google Clone{% endblock %}

{% block content %}
{% load static %}
<div class="logo">
    <img src="{% static 'myapp/resources/google-logo.png' %}" alt="Google Logo">
</div>
<form action="https://www.google.com/search" method="get">
    <input type="text" name="q" placeholder="Search...">
    <div class="buttons">
        <button type="submit">Google Search</button>
        <button type="submit" name="btnI" value="I'm Feeling Lucky">I'm Feeling Lucky</button>
    </div>
</form>
<div class="footer">
    <div class="footer-row">
        <span class="footer-text">Saudi Arabia</span>
    </div>
    <div class="footer-row2">
        <span class="footer-links">
            <a href="#">About</a> | 
            <a href="#">Advertising</a> | 
            <a href="#">How It Works</a>
        </span>
    </div>
    <div class="footer-row2">
        <span class="footer-links float-right">
            <a href="#">Privacy</a> | 
            <a href="{% url 'myapp:terms_of_service' %}">Terms of Service</a> | 
            <a href="#">Settings</a>
        </span>
    </div>
</div>

{% endblock %}

GoogleProject/myapp/templates/myapp/terms_of_service.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block title %}Terms of Service{% endblock %}

{% block content %}
    <img src="{% static 'myapp/images/terms.jpg' %}" alt="Terms Image">
    <h1>Google Terms of Service</h1>
    <p>Effective 5 January 2022</p>
    <p>Country version: Saudi Arabia</p>
    <p>We know it's tempting to skip these Terms of Service...</p>
{% endblock %}