GooglePage/GooglePage/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include("main.urls"))
]

GooglePage/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('',views.home_view , name='home_view'),
    path('Service' , views.service_view , name='service_view') 
]

GooglePage/main/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpRequest , HttpResponse 


def home_view(request:HttpRequest):
    
    return render(request , "main/home.html")

def service_view(request:HttpRequest):

    return render(request , "main/service.html")

GooglePage/main/templates/main/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/css/home_page.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" />  
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
    <header>
        <nav>
            <a href="">Gmail</a>
            <a href="">Images</a>
            <span class="material-symbols-outlined">apps</span>
            <button class="btn">Sign In</button>
        </nav>
    </header>
    {% block content %}
    
    {% endblock %}
    <footer>
        <div class="footer-section-1">
            Saudi Arabia
        </div>
        <div class="footer-section-2">
            <div>
                <a href="">About</a>
                <a href="">Advertising</a>
                <a href="">Business</a>
                <a href="">How Search Works</a>
            </div>
            <div>
                <a href="">Privacy</a>
                <a href="{%url 'main:terms_view'%}">Terms</a>
                <a href="">Settings</a>
            </div>
            
        </div>
    </footer>
</body>
</html>

GooglePage/main/templates/main/control.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/homeStyle.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20,400,0,0&"/>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Google</title>
    </head>
        <body>
             <div class="box">
                <nav class="navbar">
                    <a href="#" class="nav-item">Gmail</a>
                    <a href="#" class="nav-item">Images</a>
                    <span class="material-symbols-outlined">apps</span>
                    <button class="click1">Sign in </button>
                </nav>
             </div>
             <main>
                {%block content%}
                {%endblock%}
            </main>       
        </body>
</html>  

GooglePage/main/templates/main/home.html
{%  extends 'main/control.html'%}
{% block content %}
{%load static%}
<section class="edit-center">
    <img src="{% static 'images/google-logo.png' %}" alt="Google Logo" class="google-image">
    <div class="search-container">
        <img src="{% static 'icons/search_.png' %}" alt="Search Icon" class="icon-search">
        <input type="text" id="edit-input" placeholder="Search Google or type a URL">
        <div class="edit-images">
            <img src="{% static 'icons/mircophone.png' %}" alt="Microphone Icon" class="icon-microphone">
            <img src="{% static 'icons/camera.png' %}" alt="Camera Icon" class="icon-camera">       
        </div>       
    </div> 
    <div class="button-container">
        <button class="btnser">Google Search</button>
        <button class="btnfee"> <a href="{% url 'main:service_view' %}">I'm Feeling Lucky</a></button>
    </div>
    <div class="language-offer">
        Google offered in: <a href="#">العربية</a>
    </div>
</section>
<footer class="footer">
    <div class="footer-top">
        <span>Saudi Arabia</span>
    </div>
    <div class="footer-links">
        <div class="left-links">
            <a href="#">About</a>
            <a href="#">Advertising</a>
            <a href="#">Business</a>
            <a href="#">How Search works</a>
        </div>
        <div class="right-links">
            <a href="#">Privacy</a>
            <a href="#">Terms</a>
            <a href="#">Settings</a>
        </div>
    </div>
</footer>
{% endblock %}

GooglePage/main/templates/main/home_page.html
{% extends 'main/base.html' %}
{%load static%}
{%block title%}Google{%endblock%}
{% block content %}
<form action="https://www.google.com/search" method="GET">
<div class="content">
    <img src="{%static 'images/google-logo.png'%}"/>

    <div class="search-bar">
        <aside>
            <button type="submit"><span class="material-symbols-outlined">search</span></button>
        </aside>
        <aside>
            <input type="text" id="search" name="q"/>
        </aside>
        <aside>
            <a href=""><img src="{%static 'images/mircophone.png'%}"/></a>
            <a href=""><img src="{%static 'images/camera.png'%}"/></a>
        </aside>    
    </div>
    <div class="search-buttons">
        <button type="submit" class="btn light">Google Search</button>
        <button type="submit" class="btn light">I'm Feeling Lucky</button>
    </div>
    <div class="caption">
        <p>Google offered in: <a href="">العربية</a></p>
    </div>    
</div><!--end content-->
</form> 

{% endblock %}

GooglePage/main/templates/main/service.html
{%  extends 'main/control.html'%}
{% block content %}
{%load static%}

<section class="edit-page-S">
    <div> 
        <img src="{% static 'images/tos_main_.png' %}" alt="Google Service" class="google-service">

        </div>
    </section>
    <section class="edit-text">
        <div>
            <h3>Google Terms of Service</h3>
            <p>
                Effective 5 January 2022 | <a href="#">Archived versions</a> | <a href="#">Download PDF</a><br>
                Country version: Saudi Arabia
            </p>
            <p>
                What’s covered in these terms
                <ul>
                    <li>What you can expect from us, which describes how we provide and develop our services</li>
                    <li>What we expect from you, which establishes certain rules for using our services</li>
                    <li>Content in Google services, which describes the intellectual property rights to the content that you find in our services – whether that content belongs to you, Google or others</li>
                    <li>In case of problems or disagreements, which describes other legal rights that you have, and what to expect in case someone violates these terms.</li>
                </ul>
                Understanding these terms is important because, by using our services, you’re agreeing to these terms.
                Besides these terms, we also publish a <a href="#">Privacy Policy</a>. Although it’s not part of these terms, we encourage you to read it to better understand how you can update, manage, export, and delete your information.
            </p>
            <p>
                Terms<br>
                Service provider<br>
                Google services are provided by, and you’re contracting with:<br>
                Google LLC, organized under the laws of the State of Delaware, USA, and operating under the laws of the USA<br>
                1600 Amphitheatre Parkway, Mountain View, California 94043, USA
            </p>
            <p>
                Age requirements<br>
                If you’re under the age required to manage your own Google Account, you must have your parent or legal guardian’s permission to use a Google Account. Please ask your parent or legal guardian to read these terms with you.
            </p>
        </div>
    </section>


{% endblock %}

GooglePage/main/templates/main/terms_page.html
{%extends 'main/base.html'%}
{%load static%}
{%block title%}Terms{%endblock%}

{% block content %}

<section class="term-content">
    <img src="{%static 'images/tos_main_illustration.svg'%}"/>
    <div class="terms-text">
        <h3>Google Terms of Service</h3>
        <p>Effective 5 January 2022 | <a href="">Archived versions</a> | <a href="">Download PDF</a> </p>
        <p><a href="">Country version</a>: Saudi Arabia</p>
        <h5>What’s covered in these terms</h5>
        <h6>We know it’s tempting to skip these Terms of Service, but it’s important to establish what you can expect from us as you use Google <a href="">services</a>, and what we expect from you.</h6>
        <p>These Terms of Service reflect <a href="">the way that Google’s business works</a>, the laws that apply to our company, and <a href="">certain things that we’ve always believed to be true</a>. As a result, these Terms of Service help define Google’s relationship with you as you interact with our services. For example, these terms include the following topic headings:</p>
        <ul>
            <li><a href="">What you can expect from us</a> which describes how we provide and develop our services</li>
            <li><a href="">What we expect from you</a> which establishes certain rules for using our services</li>
            <li><a href="">Content in Google services</a>, which describes the intellectual property rights to the content that you find in our services – whether that content belongs to you, Google or others</li>
            <li><a href="">In case of problems or disagreements</a>, which describes other legal rights that you have, and what to expect in case someone violates these terms.</li>
       </ul>
        <p>Understanding these terms is important because, by using our services, you’re agreeing to these terms.</p>
        <p>Besides these terms, we also publish a <a href="">Privacy Policy</a> Although it’s not part of these terms, we encourage you to read it to better understand how you can <a href="">update, manage, export and delete your information</a></p>

        <h3>Terms</h3>
        <h5>Service provider</h5>
        <p>Google <a href="">services</a> are provided by, and you’re contracting with:</p>
        <p>Google LLCorganised under the laws of the State of Delaware, USA, and operating under the laws of the USA1600 Amphitheatre ParkwayMountain View, California 94043USA</p>

        <h3>Age requirements</h3>
        <p>If you’re under the <a href="">age required to manage your own Google Account</a>, you must have your parent or legal guardian’s permission to use a Google Account. Please ask your parents or legal guardian to read these terms with you.</p>
        <p>If you’re a parent or legal guardian, and you allow your child to use the <a href="">services</a>, then these terms apply to you and you’re responsible for your child’s activity on the services.</p>
        <p>Some Google services have additional age requirements as described in their <a href="">service-specific additional terms and policies</a>.</p>

    </div>


</section>

{%endblock%}